language: java

jdk:
  - openjdk8
  - openjdk11

env:
  - OWLAPI_VERSION=4.2.8
  - OWLAPI_VERSION=4.5.15
  - OWLAPI_VERSION=5.1.11
  - OWLAPI_VERSION=5.1.12
  - OWLAPI_VERSION=5.1.13

cache:
  directories:
  - $HOME/.m2
